name: macOS 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos_test:
    name: Build OpenObservation on macOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15]
        xcode-version: ["16.4"]   # Swift 6.1.2
    runs-on: ${{ matrix.os }}
    env:
      OPENOBSERVATION_WERROR: 1
      OPENOBSERVATION_DEVELOPMENT: 0
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode
        uses: OpenSwiftUIProject/OpenSwiftUI/.github/actions/setup-xcode@main
        with:
          xcode-version: ${{ matrix.xcode-version }}
      - name: Swift version
        run: swift --version
      - name: Build in debug mode
        run: |
          swift build -c debug
      - name: Build in release mode
        run: |
          swift build -c release